# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yauth}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matteo Collina"]
  s.date = %q{2011-03-02}
  s.default_executable = %q{yauth}
  s.description = %q{Yauth is a extremely simple authentication solution for prototipes, developed as a warden strategy. It uses a yaml file to store usernames and hashed password. It provides a better-than-nothing security.}
  s.email = %q{matteo@matteocollina.com}
  s.executables = ["yauth"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".document",
    ".rspec",
    ".rvmrc",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/yauth",
    "examples/sinatra/app.rb",
    "examples/sinatra/config/users.yml",
    "lib/yauth.rb",
    "lib/yauth/cli.rb",
    "lib/yauth/failure_app.rb",
    "lib/yauth/strategy.rb",
    "lib/yauth/user.rb",
    "lib/yauth/user_manager.rb",
    "spec/spec_helper.rb",
    "spec/yauth/cli_spec.rb",
    "spec/yauth/failure_app_spec.rb",
    "spec/yauth/strategy_spec.rb",
    "spec/yauth/user_manager_spec.rb",
    "spec/yauth/user_spec.rb",
    "spec/yauth_spec.rb",
    "yauth.gemspec"
  ]
  s.homepage = %q{http://github.com/mcollina/yauth}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.3}
  s.summary = %q{A drop-in authentication solution for prototypes.}
  s.test_files = [
    "examples/sinatra/app.rb",
    "spec/spec_helper.rb",
    "spec/yauth/cli_spec.rb",
    "spec/yauth/failure_app_spec.rb",
    "spec/yauth/strategy_spec.rb",
    "spec/yauth/user_manager_spec.rb",
    "spec/yauth/user_spec.rb",
    "spec/yauth_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bcrypt>, ["~> 2.1.4"])
      s.add_runtime_dependency(%q<warden>, ["~> 1.0"])
      s.add_runtime_dependency(%q<thor>, ["~> 0.14.0"])
      s.add_development_dependency(%q<test_notifier>, ["~> 0.3.6"])
      s.add_development_dependency(%q<autotest>, ["~> 4.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<bcrypt>, ["~> 2.1.4"])
      s.add_dependency(%q<warden>, ["~> 1.0"])
      s.add_dependency(%q<thor>, ["~> 0.14.0"])
      s.add_dependency(%q<test_notifier>, ["~> 0.3.6"])
      s.add_dependency(%q<autotest>, ["~> 4.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<bcrypt>, ["~> 2.1.4"])
    s.add_dependency(%q<warden>, ["~> 1.0"])
    s.add_dependency(%q<thor>, ["~> 0.14.0"])
    s.add_dependency(%q<test_notifier>, ["~> 0.3.6"])
    s.add_dependency(%q<autotest>, ["~> 4.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

